on:
  push:
    branches:
      -main
    paths:
      - '**.md'
jobs:
  get-md-files:
    runs-on: ubuntu-latest
    steps:
      - name: Get MD files
        run: |
          ls -R

          
      